name: Connector Ops CI - Connector Metadata Checks

on:
  pull_request:
    paths:
      - "airbyte-integrations/connectors/source-**"
permissions:
  contents: read

jobs:
  connector-metadata-checks:
    name: "Check Connector Metadata"
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout Airbyte
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.9"
      - name: Install ci-connector-ops package
        run: pip install --quiet -e ./tools/ci_connector_ops
      - name: Check test strictness level
        run: check-test-strictness-level
      - name: Check allowed hosts
        run: allowed-hosts-checks
