name: Add Connector Merge Checklist
on:
  pull_request_target:
    types: [opened, reopened]
    paths:
      - "airbyte-integrations/connectors/source-**"
      - "airbyte-integrations/connectors/destination-**"
      - "airbyte-integrations/connectors/third-party/**"
permissions:
  contents: read
jobs:
  checklist_job:
    name: Add Connector Merge Checklist Job
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Checklist
        uses: wyozi/contextual-qa-checklist-action@dd4b6b51d85a59f537b7ca9e2f162164627ec811 # master
        with:
          comment-header: "### Before Merging a Connector Pull Request \n\n Wow! What a great pull request you have here! 🎉 \n\n To merge this PR, ensure the following has been done/considered for each connector added or updated: \n\n"
          comment-footer: "If the checklist is complete, but the CI check is failing, \n\n1. Check for hidden checklists in your PR description \n\n2. Toggle the github label `checklist-action-run` on/off to re-run the checklist CI."
          show-paths: false
          input-file: airbyte-ci/connectors/CONNECTOR_CHECKLIST.yaml
          gh-token: ${{ secrets.GITHUB_TOKEN }}
