name: Deploy docs.airbyte.com

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "docusaurus/**"

  pull_request:
    types:
      - closed
      - opened
      - reopened
      - synchronize
    paths:
      - "docs/**"
      - "docusaurus/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    name: Build and Deploy Docs Assets
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Check out the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      # Node.js is needed for Yarn
      - name: Setup Yarn
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "16.14.0"
          cache: "yarn"
          cache-dependency-path: docusaurus


      - name: Run Docusaurus
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_APPROVINGTON_OCTAVIA }}
        run: |-
          export SKIP_DEPLOY="yes"
          if [ "${{github.event_name}}" = 'push' -o "${{github.event_name}}" = 'workflow_dispatch' -o "${{github.event.pull_request.merged}}" = 'true' ]; then
              export SKIP_DEPLOY="no"
          fi

          ./tools/bin/deploy_docusaurus


      - name: Notify Slack -- deploy failed
        if: always() && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && job.status != 'success'
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
        with:
          # 'C02TYDSUM8F' => '#dev-deploys'
          # 'C03BEADRPNY' => '#docs'
          args: >-
            {\"channel\":\"C03BEADRPNY\",\"attachments\":[
            {\"color\":\"#ff0000\",\"blocks\":[
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"OSS Docs deploy fails on the latest master :bangbang:\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged by_: *${{ github.actor }}*\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Action Run>\"}}
            ]}]}

      - name: Notify Slack -- deploy succeeded
        if: always() && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && job.status == 'success'
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
        with:
          # 'C02TYDSUM8F' => '#dev-deploys'
          # 'C03BEADRPNY' => '#docs'
          args: >-
            {\"channel\":\"C03BEADRPNY\",\"attachments\":[
            {\"color\":\"#00ff00\",\"blocks\":[
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"OSS Docs deploy was successful :tada:\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged by_: *${{ github.actor }}*\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Action Run>\"}}
            ]}]}
