name: Connector metadata service deploy orchestrator

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "airbyte-ci/connectors/metadata_service/orchestrator/**"
jobs:
  connector_metadata_service_deploy_orchestrator:
    name: Connector metadata service deploy orchestrator
    runs-on: medium-runner
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout Airbyte
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Deploy the metadata orchestrator
        id: metadata-orchestrator-deploy-orchestrator-pipeline
        uses: ./.github/actions/run-dagger-pipeline
        with:
          subcommand: "metadata deploy orchestrator"
          context: "master"
          github_token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
          docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        env:
          DAGSTER_CLOUD_METADATA_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_METADATA_API_TOKEN }}
