name: Deprecation message for publish slash command
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repo to check out code from. Defaults to the main airbyte repo. Set this when building connectors from forked repos."
        required: false
        default: "airbytehq/airbyte"
      gitref:
        description: "The git ref to check out from the specified repository."
        required: false
        default: master
      connector:
        description: "Airbyte Connector"
        required: true
      comment-id:
        description: "The comment-id of the slash command. Used to update the comment with the status."
        required: false
      parallel:
        description: "Switching this to true will spin up 5 build agents instead of 1 and allow multi connector publishes to run in parallel"
        required: true
        default: "false"
      run-tests:
        description: "Should run tests when publishing"
        required: true
        default: "true"
      pre-release:
        description: "Should publish a pre-release version"
        required: true
        default: "false"

permissions:
  contents: read

jobs:
  write-deprecation-message:
    permissions:
      issues: write  # for peter-evans/create-or-update-comment to create or update comment
      pull-requests: write  # for peter-evans/create-or-update-comment to create or update comment
    name: Set up git comment
    if: github.event.inputs.comment-id
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Print deprecation message
        if: github.event.inputs.comment-id
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae # v1.4.5
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :warning: The publish slash command is now deprecated.<br>
            The connector publication happens on merge to the master branch.<br>
            Please use /legacy-publish if you need to publish normalization images.<br>
            Please join the #publish-on-merge-updates slack channel to track ongoing publish pipelines.<br>
            Please reach out to the @dev-connector-ops team if you need support in publishing a connector.
