name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    # Only allow slash commands on pull request (not on issues)
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Get PR repo and ref
        id: getref
        run: |
          pr_info="$(curl ${{ github.event.issue.pull_request.url }})"
          echo ref="$(echo $pr_info | jq -r '.head.ref')" >> $GITHUB_OUTPUT
          echo repo="$(echo $pr_info | jq -r '.head.repo.full_name')" >> $GITHUB_OUTPUT

      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@40877f718dce0101edfc7aea2b3800cc192f9ed5 # v2.3.0
        with:
          token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
          permission: write
          commands: |
            test
            legacy-test
            test-performance
            build-connector
            publish-connector
            publish
            legacy-publish
            publish-external
            gke-kube-test
            run-specific-test
            connector-performance
          static-args: |
            repo=${{ steps.getref.outputs.repo }}
            gitref=${{ steps.getref.outputs.ref }}
            comment-id=${{ github.event.comment.id }}
          dispatch-type: workflow

      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae # v1.4.5
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > Error: ${{ steps.scd.outputs.error-message }}
